# Generated by Django 4.2.10 on 2024-02-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 51, 14, 46521)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 51, 14, 44832)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 51, 14, 46788)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 51, 14, 46777)),
        ),
    ]
