# Generated by Django 4.2.10 on 2024-02-19 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 16, 26, 141660)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 16, 26, 140185)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 16, 26, 141920)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 16, 26, 141909)),
        ),
    ]
