# Generated by Django 4.2.10 on 2024-02-19 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0002_alter_carsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 27, 48, 295715)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 27, 48, 293953)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 27, 48, 295973)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 18, 27, 48, 295962)),
        ),
    ]
