# Generated by Django 4.2.10 on 2024-02-19 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0002_alter_car_created_at_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 20, 29, 706230)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 20, 29, 704738)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 20, 29, 706489)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 20, 29, 706478)),
        ),
    ]
