# Generated by Django 4.2.10 on 2024-02-20 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0003_alter_carsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 48, 58, 309691)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 48, 58, 308093)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 48, 58, 309976)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 48, 58, 309964)),
        ),
    ]
