# Generated by Django 4.2.10 on 2024-02-20 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory_management', '0004_alter_carsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 53, 5, 204584)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 53, 5, 203078)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 53, 5, 204846)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 53, 5, 204834)),
        ),
    ]
